// Generated by https://quicktype.io

export interface Order {
    id:           number;
    productId:    number;
    productName:  string;
    customerName: string;
    orderDate:    string;
    amount:       number;
    price:        number;
    totalPrice:   number;
}
