// Generated by https://quicktype.io

export interface Product {
    id:          number;
    name:        string;
    description: string;
    price:       number;
    category:    string;
    stock:       number;
    reviews:     null;
}
