// Generated by https://quicktype.io

export interface User {
    id:          number;
    name:        string;
    email:       string;
    address:     string;
    phoneNumber: string;
    password:    string;
    role:        string;
}
